apn_server:
  host: 'gateway.sandbox.push.apple.com' #'gateway.push.apple.com'
  port: '2195'
  ssl_pem: '' #Push certificate file name
  key: '' #Push certificate service password
  
queue:
  type: 'activemq'
  name: 'apn_queue'
